### ISSUE TITLE
Implement channels and channel switcher

### ISSUE THREAD

**Issue by zaiste** [saleor/storefront#1016]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/storefront/issues/971
- [ ] https://github.com/saleor/storefront/issues/1028
- [ ] https://github.com/saleor/storefront/issues/1029
- [ ] https://github.com/saleor/storefront/issues/1017
```
