### ISSUE TITLE
Update storefront/checkout to use the new flow

### ISSUE THREAD

**Issue by mmiszy** [saleor/storefront#864]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/13016
- [x] Update storefront/checkout to use the new flow with Adyen
- [x] Remove payment-related backend from the checkout
```
