### ISSUE TITLE
Implementing BTC Pay Server for Payments (Stripe of BTC and Lightning)

### ISSUE THREAD

**Issue by maektwain** [saleor/storefront#866]
### Discussed in https://github.com/saleor/react-storefront/discussions/865

<div type='discussions-op-text'>

<sup>Originally posted by **maektwain** July  4, 2023</sup>
What is BTCPay Server?

 It is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant and free.

The custom integration API is https://docs.btcpayserver.org/CustomIntegration/

Ideally a concerned user might host their own server but for now they can use a third party service https://docs.btcpayserver.org/Deployment/ThirdPartyHosting/

Then we need a checkout-app that may create store and wallet address from dashboard , and then most part is handled by the BTC pay server,

We are willing to give bounty or funds to whomsoever decides to implement this. 

Thanks </div>
```[tasklist]
### Tasks
- [ ] Create detailed tech spec
- [ ] Find or fund developer who can implement this
- [ ] Reuse and distribute as open source
```
